---
- hosts: all
  vars:
    env_dir: /var/juiz/environment
  tasks:
  - name: wait for ssh to start
    local_action: "wait_for port=22 host={{ansible_ssh_host}} search_regex=OpenSSH"
  - name: create working directory
    file: path=/var/juiz state=directory
  - name: install dependencies
    yum: pkg={{item}} state=latest
    with_items:
      - rsync
      - firewalld
      - sudo
  - name: enabling firewalld
    service: name=firewalld.service enabled=yes state=started
  - name: copy juiz runtime
    synchronize: src={{runtime}}/ dest={{runtime_dir}} recursive=yes delete=yes
  - name: clear environment directory
    file: path={{env_dir}} state=absent
  - name: create environment directory
    file: path={{env_dir}} state=directory
  - name: dump host environment
    copy: dest={{env_dir}}/{{item.key}} content={{item.value}}
    with_dict: host_env