---
- hosts: all
  gather_facts: no
  tasks:
  - name: wait for ssh to start
    local_action: "wait_for port=22 host={{ansible_ssh_host}} search_regex=OpenSSH"
- hosts: install_ssh
  gather_facts: no
  tasks:
  - name: install ssh host key
    authorized_key: user=root key={{ansible_ssh_private_key_file}}
- hosts: all
  vars:
    env_dir: /var/juiz/environment
  tasks:
  - name: create working directory
    file: path=/var/juiz state=directory
  - name: update apt cache
    apt: update_cache=yes
  - name: install dependencies
    apt: name={{item}} state=latest
    with_items:
      - rsync
      - ufw
      - sudo
  - name: enable ufw
    ufw: state=enabled policy=reject
  - name: enable ssh in firewall
    ufw: rule=limit port=ssh
  - name: copy juiz runtime
    synchronize: src={{runtime}}/ dest={{runtime_dir}} recursive=yes delete=yes
  - name: clear environment directory
    file: path={{env_dir}} state=absent
  - name: create environment directory
    file: path={{env_dir}} state=directory
  - name: dump host environment
    copy: dest="{{env_dir}}/{{item.key}}" content="{{item.value}}"
    with_dict: host_env