---
- hosts: all
  tasks:
  - name: wait for ssh to start
    local_action: "wait_for port=22 host={{ansible_ssh_host}} search_regex=OpenSSH"
  - name: create working directory
    file: path=/var/juiz state=directory
  - name: install dependencies
    yum: pkg={{item}} state=latest
    with_items:
      - rsync
      - firewalld
  - name: enabling firewalld
    service: name=firewalld.service enabled=yes state=started
  - name: copy juiz runtime
    synchronize: src={{runtime}}/ dest={{runtime_dir}} recursive=yes delete=yes