---
- hosts: memcache
  tasks:
  - name: install memcache
    apt: name=memcached state=latest
  - name: allow memcache access from web machines
    ufw: rule=allow proto=tcp from_ip="{{item}}" port="11211"
    with_items: web_ip
  - name: start memcache
    service: name=memcached enabled=yes state=started