---
- hosts: web
  vars:
    app_dir: /var/juiz/source
    cache_dir: /var/juiz/build_cache
    env_dir: /var/juiz/environment
  tasks:
  # system
  - name: install dependencies
    apt: name={{item}} state=latest
    with_items:
      - git
      - ruby
      - rsync
      - python-yaml
      - python-jinja2
      - nginx
      - libpq5 # php implicitly requires this
      - libpq-dev
      - libltdl7 # php implicitly requires this
      # libmariadbclient-dev cause compilation error
      # see: https://mariadb.atlassian.net/browse/MDEV-6862
      - libmysqlclient-dev # python implicitly requires this
  - name: create app user
    user: name=app createhome=no home=/app shell=/sbin/nologin

  # env
  - name: dump environment to directory
    copy: dest="{{env_dir}}/{{item.key}}" content="{{item.value}}" owner=app
    with_dict: env

  # buildpack
  - name: clone buildpack
    git: repo={{buildpack.source}} dest=/var/juiz/buildpack update=yes
    notify:
    - compile source

  # source
  - name: upload source
    synchronize: src={{project.root}}/ dest={{app_dir}} recursive=yes delete=yes
    notify:
    - compile source

  # compile
  - meta: flush_handlers
  - name: generate units
    command: /usr/bin/python2 /var/juiz/remote/unit-generator.py
  - meta: flush_handlers

  # services
  - name: enable web unit
    service: name=juiz-web enabled=yes state=restarted
  - name: generate nginx configuration
    template: src=../data/web/nginx.conf dest=/etc/nginx/sites-enabled/default owner=root mode=640
    notify:
    - reload nginx

  # firewall
  - name: enable firewall for http
    ufw: rule=allow port=http
  handlers:
  - name: compile source
    shell: "{{runtime_dir}}/compile {{app_dir}} {{cache_dir}} {{env_dir}}"

  # services
  - name: reload nginx
    service: name=nginx enabled=yes state=reloaded