# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Mon Jan  5 16:40:20 2015
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from wx.lib.agw.ultimatelistctrl import UltimateListCtrl
# end wxGlade


class BuildpackList(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: BuildpackList.__init__
		kwds["style"] = wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.buildpack_list = UltimateListCtrl(self, 1000, agwStyle=wx.LC_REPORT|wx.LC_VRULES|wx.LC_HRULES)
		self.btn_add = wx.Button(self, wx.ID_ADD, "")
		self.btn_remove = wx.Button(self, wx.ID_REMOVE, "")
		self.btn_close = wx.Button(self, wx.ID_CLOSE, "")

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: BuildpackList.__set_properties
		self.SetTitle(_("Buildpack management"))
		self.SetSize((300, 400))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: BuildpackList.__do_layout
		sizer_13 = wx.BoxSizer(wx.VERTICAL)
		sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_13.Add(self.buildpack_list, 1, wx.EXPAND, 0)
		sizer_14.Add(self.btn_add, 0, wx.RIGHT | wx.ADJUST_MINSIZE, 5)
		sizer_14.Add(self.btn_remove, 0, wx.RIGHT | wx.ADJUST_MINSIZE, 5)
		sizer_14.Add(self.btn_close, 0, wx.ADJUST_MINSIZE, 0)
		sizer_13.Add(sizer_14, 0, wx.TOP | wx.BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 10)
		self.SetSizer(sizer_13)
		self.Layout()
		self.Centre()
		# end wxGlade

# end of class BuildpackList
