# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Jan  6 12:11:45 2015
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from wx.lib.agw.ultimatelistctrl import UltimateListCtrl, ULC_HAS_VARIABLE_ROW_HEIGHT
# end wxGlade


class LogViewer(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: LogViewer.__init__
		kwds["style"] = wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		self.label_5 = wx.StaticText(self, wx.ID_ANY, _("Search:"))
		self.search = wx.SearchCtrl(self, 1000, "")
		self.panel_2 = wx.Panel(self, wx.ID_ANY)
		self.logname = wx.Choice(self, 1001, choices=[])
		self.loglevel = wx.Choice(self, 1002, choices=[])
		self.log = wx.ListCtrl(self, 2000, style=wx.LC_REPORT|wx.LC_VRULES|wx.LC_HRULES)
		self.statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: LogViewer.__set_properties
		self.SetTitle(_("Log viewer"))
		self.SetSize((600, 500))
		self.panel_2.SetMinSize((60, 20))
		self.logname.SetMinSize((170, 28))
		self.loglevel.SetMinSize((100, 28))
		self.statusbar.SetStatusWidths([-1])
		# statusbar fields
		statusbar_fields = [""]
		for i in range(len(statusbar_fields)):
		    self.statusbar.SetStatusText(statusbar_fields[i], i)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: LogViewer.__do_layout
		sizer_15 = wx.BoxSizer(wx.VERTICAL)
		sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_16.Add(self.label_5, 0, wx.LEFT | wx.RIGHT | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 5)
		sizer_16.Add(self.search, 1, wx.TOP | wx.BOTTOM | wx.EXPAND | wx.ADJUST_MINSIZE, 5)
		sizer_16.Add(self.panel_2, 0, 0, 0)
		sizer_16.Add(self.logname, 0, wx.RIGHT | wx.TOP | wx.ADJUST_MINSIZE, 5)
		sizer_16.Add(self.loglevel, 0, wx.RIGHT | wx.TOP | wx.ADJUST_MINSIZE, 5)
		sizer_15.Add(sizer_16, 0, wx.EXPAND, 0)
		sizer_15.Add(self.log, 1, wx.EXPAND, 0)
		self.SetSizer(sizer_15)
		self.Layout()
		self.Centre()
		# end wxGlade

# end of class LogViewer
