---
- hosts: web
  tasks:
  - name: install dependencies
    yum: pkg={{item}} state=latest
    with_items:
      - git
      - python
      - ruby
      - rsync
  - name: clone buildpack
    git: repo={{buildpack.source}} dest=/var/juiz/buildpack update=yes
  - name: upload source
    synchronize: src={{project.root}}/ dest=/var/juiz/source recursive=yes